export const adminBreadcrumb: Record<string, string> = {
  '/admin': 'Dashboard',
  '/admin/profil': 'Profil Saya',
  '/admin/profil/ubah-password': 'Ubah Password',
  '/admin/peminjaman/ajuan': 'Ajuan Peminjaman',
  '/admin/peminjaman/ajuan/[id]': 'Detail',
  '/admin/peminjaman/riwayat': 'Riwayat Peminjaman',
  '/admin/peminjaman/riwayat/[id]': 'Detail',
  '/admin/peminjaman/form': 'Buat Peminjaman',
  '/admin/ruangan/jadwal-ketersediaan': 'Jadwal Ketersediaan',
  '/admin/ruangan': 'Daftar Ruangan',
  '/admin/ruangan/[id]': 'Detail',
  '/admin/ruangan/edit/[id]': 'Edit',
  '/admin/ruangan/tambah': 'Tambah',
};
